- Numpy :-
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [2]:
import numpy as np

In [3]:
# Creating 1D Array
arr = np.array([1,2,3,4,5])
print('Array :',arr)
print('Shape :',arr.shape)
print('Type :',type(arr))

Array : [1 2 3 4 5]
Shape : (5,)
Type : <class 'numpy.ndarray'>


In [5]:
# Reshapeing 1D Array

reshape_arr = arr.reshape(1,5) # 1 row 5 column
print('Array before reshaped :',arr)
print('Reshaped Array :',reshape_arr)

Array before reshaped : [1 2 3 4 5]
Reshaped Array : [[1 2 3 4 5]]


In [6]:
# 2D Array 
arr1 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print('Shape of array :',arr1.shape)
print('Array :',arr1)

Shape of array : (2, 5)
Array : [[1 2 3 4 5]
 [2 3 4 5 6]]


In [7]:
# Array with range function

np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
# Creating identity matrix
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
# Attributes of array

print("Array:\n", arr1)
print("Shape:", arr1.shape)
print("Number of dimensions:", arr1.ndim)
print("Size (number of elements):", arr1.size)
print("Data type:", arr1.dtype)
print("Item size (in bytes):", arr1.itemsize)

Array:
 [[1 2 3 4 5]
 [2 3 4 5 6]]
Shape: (2, 5)
Number of dimensions: 2
Size (number of elements): 10
Data type: int64
Item size (in bytes): 8


In [13]:
# Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

# Element Wise addition
print("Addition:", arr1+arr2)

# Element Wise Substraction
print("Substraction:", arr1-arr2)

# Element-wise multiplication
print("Multiplication:", arr1 * arr2)

# Element-wise division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [15]:
# Universal Function
arr=np.array([2,3,4,5,6])
# square root
print('square root :',np.sqrt(arr))

# Exponential
print('Exponential :',np.exp(arr))

# Sine
print('Sine :',np.sin(arr))

# natural log
print('natural log :',np.log(arr))

square root : [1.41421356 1.73205081 2.         2.23606798 2.44948974]
Exponential : [  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
Sine : [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
natural log : [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [16]:
# array slicing and Indexing

arr3=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr3)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
print(arr3[0:,2:])

[[ 3  4]
 [ 7  8]
 [11 12]]


In [24]:
print(arr3[1:,1:3])

[[ 6  7]
 [10 11]]


In [27]:
# Modify array elements
arr3[1,2]=100
print(arr3)

[[  1   2   3   4]
 [  5   6 100   8]
 [  9  10  11  12]]


In [29]:
arr3[0,0]=10
print(arr3)

[[ 10   2   3   4]
 [  5   6 100   8]
 [  9  10  11  12]]


In [30]:
# statistical concepts--Normalization to have a mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [31]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [32]:
# Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])