### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [1]:
import numpy as np

In [3]:
# Queastion 1.

# Create a (5x5) array with random integers between 1 and 20
arr = np.random.randint(1, 21, size=(5, 5))

print("Original Array:")
print(arr)

# Replace all elements in the third column with 1
arr[:, 2] = 1     # column index 2 → third column

print("\nModified Array (3rd column replaced with 1):")
print(arr)

Original Array:
[[ 2 16 13  2 13]
 [19 11 20 11 17]
 [ 9 10 19  9 12]
 [20  1  6 14 15]
 [20 20 15 17 10]]

Modified Array (3rd column replaced with 1):
[[ 2 16  1  2 13]
 [19 11  1 11 17]
 [ 9 10  1  9 12]
 [20  1  1 14 15]
 [20 20  1 17 10]]


In [4]:
# Question 2.

arr1 = np.arange(0,16).reshape(4,4)
print('Orignal Array :')
print(arr1)

# Replace diagonal elements with 0
np.fill_diagonal(arr1, 0)

print("\nModified Array (Diagonal elements replaced with 0):")
print(arr1)

Orignal Array :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Modified Array (Diagonal elements replaced with 0):
[[ 0  1  2  3]
 [ 4  0  6  7]
 [ 8  9  0 11]
 [12 13 14  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [7]:
# Question 1.

arr2 = np.arange(1,37).reshape(6,6)
print('Array Before Exract ..')
print(arr2)

# Extract rows 3 to 5 → index 2 to 4
# Extract columns 2 to 4 → index 1 to 3

sub_arr2 = arr2[2:5 ,1:3]

print('\nSub array :  ')
print(sub_arr2)

Array Before Exract ..
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Sub array :  
[[14 15]
 [20 21]
 [26 27]]


In [20]:
# Question 2.

rand_arr = np.random.randint(1,100,size=(5,5))
print('Original Array :')
print(rand_arr)

# rand_arr[ start_row : end_row ,start_col:end:col ]
top_row = rand_arr[0, :] 
last_row = rand_arr[-1,:]
left_col= rand_arr[1:-1,0]
right_col = rand_arr[1:-1,-1]

border_element = np.concatenate([top_row,right_col,last_row[::-1],left_col[::-1]])

print('\nBorder elements from original array :')
print(border_element)

Original Array :
[[ 2 22 20 47 79]
 [93 42 90 84 35]
 [ 3 18 11  2 32]
 [28 57 36 53 54]
 [57 72 70 15 49]]

Border elements from original array :
[ 2 22 20 47 79 35 32 54 49 15 70 72 57 28  3 93]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.