### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [1]:
import numpy as np

In [3]:
# Queastion 1.

# Create a (5x5) array with random integers between 1 and 20
arr = np.random.randint(1, 21, size=(5, 5))

print("Original Array:")
print(arr)

# Replace all elements in the third column with 1
arr[:, 2] = 1     # column index 2 → third column

print("\nModified Array (3rd column replaced with 1):")
print(arr)

Original Array:
[[ 2 16 13  2 13]
 [19 11 20 11 17]
 [ 9 10 19  9 12]
 [20  1  6 14 15]
 [20 20 15 17 10]]

Modified Array (3rd column replaced with 1):
[[ 2 16  1  2 13]
 [19 11  1 11 17]
 [ 9 10  1  9 12]
 [20  1  1 14 15]
 [20 20  1 17 10]]


In [4]:
# Question 2.

arr1 = np.arange(0,16).reshape(4,4)
print('Orignal Array :')
print(arr1)

# Replace diagonal elements with 0
np.fill_diagonal(arr1, 0)

print("\nModified Array (Diagonal elements replaced with 0):")
print(arr1)

Orignal Array :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Modified Array (Diagonal elements replaced with 0):
[[ 0  1  2  3]
 [ 4  0  6  7]
 [ 8  9  0 11]
 [12 13 14  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [7]:
# Question 1.

arr2 = np.arange(1,37).reshape(6,6)
print('Array Before Exract ..')
print(arr2)

# Extract rows 3 to 5 → index 2 to 4
# Extract columns 2 to 4 → index 1 to 3

sub_arr2 = arr2[2:5 ,1:3]

print('\nSub array :  ')
print(sub_arr2)

Array Before Exract ..
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Sub array :  
[[14 15]
 [20 21]
 [26 27]]


In [20]:
# Question 2.

rand_arr = np.random.randint(1,100,size=(5,5))
print('Original Array :')
print(rand_arr)

# rand_arr[ start_row : end_row ,start_col:end:col ]
top_row = rand_arr[0, :] 
last_row = rand_arr[-1,:]
left_col= rand_arr[1:-1,0]
right_col = rand_arr[1:-1,-1]

border_element = np.concatenate([top_row,right_col,last_row[::-1],left_col[::-1]])

print('\nBorder elements from original array :')
print(border_element)

Original Array :
[[ 2 22 20 47 79]
 [93 42 90 84 35]
 [ 3 18 11  2 32]
 [28 57 36 53 54]
 [57 72 70 15 49]]

Border elements from original array :
[ 2 22 20 47 79 35 32 54 49 15 70 72 57 28  3 93]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [25]:
# Question 1.

arr1 = np.random.randint(1,20,size=(3,4))
arr2 = np.random.randint(1,20,size=(3,4))
print('Original Arrays')
print(arr1)
print(arr2)

print('Operations on Array')

# Addition,Substraction,multiplication,Division

add_arr = arr1+arr2
subs_arr = arr1-arr2
mult_arr = arr1*arr2
div_arr = arr1/arr2

print('\nAddition :',add_arr)
print('\nSubstraction :',subs_arr)
print('\nMultiply :',mult_arr)
print('\nDivison :',div_arr)


Original Arrays
[[12  9 14 19]
 [12 10 10  7]
 [ 4  7 18  8]]
[[14 15 14  9]
 [18  6  2  4]
 [ 3 12  9 12]]
Operations on Array

Addition : [[26 24 28 28]
 [30 16 12 11]
 [ 7 19 27 20]]

Substraction : [[-2 -6  0 10]
 [-6  4  8  3]
 [ 1 -5  9 -4]]

Multiply : [[168 135 196 171]
 [216  60  20  28]
 [ 12  84 162  96]]

Divison : [[0.85714286 0.6        1.         2.11111111]
 [0.66666667 1.66666667 5.         1.75      ]
 [1.33333333 0.58333333 2.         0.66666667]]


In [28]:
# Question 2.

new_arr = np.arange(1,17).reshape(4,4)
print('original array ')
print(new_arr)

# Row-wise sum
row_sum = new_arr.sum(axis=1)
print('\nRow-wise sum :')
print(row_sum)

# Column-wise sum
col_sum = new_arr.sum(axis=0)
print('\ncolumn-wise sum :')
print(col_sum)

original array 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Row-wise sum :
[10 26 42 58]

column-wise sum :
[28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [33]:
# Question 1.

arry = np.random.randint(1,40,size=(5,5))
print('Original Array :')
print(arry)

# mean, median, standard deviation, and variance

arr_mean = np.mean(arry)
arr_med = np.median(arry)
arr_std = np.std(arry)
arr_var = np.var(arry)

print("\nMean:", arr_mean)
print("Median:", arr_med)
print("Standard Deviation:", arr_std)
print("Variance:", arr_var)

Original Array :
[[34  1 35 38 31]
 [ 8 12  9 28 14]
 [14 22 23 11  8]
 [26 23 23  6 39]
 [ 3  8  7  3 36]]

Mean: 18.48
Median: 14.0
Standard Deviation: 12.050294602207865
Variance: 145.20960000000002


In [34]:
import numpy as np

# Create 3x3 array with values 1 to 9
arr = np.arange(1, 10).reshape(3, 3)

print("Original Array:")
print(arr)

# Compute mean and std
mean_val = np.mean(arr)
std_val = np.std(arr)

# Normalize the array
normalized_arr = (arr - mean_val) / std_val

print("\nNormalized Array:")
print(normalized_arr)

print("\nMean after normalization:", normalized_arr.mean())
print("Std after normalization:", normalized_arr.std())


Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Normalized Array:
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]

Mean after normalization: 0.0
Std after normalization: 1.0


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [36]:
# Question 1.

new2d_arr1 = np.random.randint(1,30,size=(3,3))
print(' Original array  ')
print(new2d_arr1)

# 1D Array for adding
new1d_arr = np.array([10, 20, 30])
print("\n1D Array to Add:")
print(new1d_arr)

# Broadcasting: Add 1D array to each row
result = new2d_arr1 + new1d_arr

print("\nResult After Broadcasting (row-wise addition):")
print(result)

 Original array  
[[26 12 16]
 [24 18  7]
 [ 3 10 13]]

1D Array to Add:
[10 20 30]

Result After Broadcasting (row-wise addition):
[[36 32 46]
 [34 38 37]
 [13 30 43]]


In [37]:
# Question 2.

new2D_arr1 = np.random.randint(1,40,size=(4,4))
print(' Original array  ')
print(new2D_arr1)

# 1D Array for Substraction
new1D_arr = np.array([2, 4, 6, 8])
print("\n1D Array to Substract:")
print(new1D_arr)

# Broadcasting: Substract 1D array to each row
result = new2D_arr1 - new1D_arr

print("\nResult After Broadcasting (row-wise substraction):")
print(result)

 Original array  
[[16  8  9 31]
 [26 14  9 26]
 [ 1 38 11 12]
 [20  7 36 15]]

1D Array to Substract:
[2 4 6 8]

Result After Broadcasting (row-wise substraction):
[[14  4  3 23]
 [24 10  3 18]
 [-1 34  5  4]
 [18  3 30  7]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [38]:
# Question 1.
import numpy as np

# Create a 3x3 matrix (use floats to avoid integer division surprises)
A = np.array([[4.0, 7.0, 2.0],
              [3.0, 5.0, 1.0],
              [2.0, 4.0, 3.0]])

np.set_printoptions(precision=6, suppress=True)  # nicer printing

print("Matrix A:")
print(A)

# Determinant
detA = np.linalg.det(A)
print("\nDeterminant of A:", detA)

# Inverse (only if determinant is not zero / not too close to zero)
if abs(detA) < 1e-12:
    print("\nMatrix is singular (determinant ~ 0). Inverse does not exist.")
else:
    A_inv = np.linalg.inv(A)
    print("\nInverse of A:")
    print(A_inv)

# Eigenvalues and eigenvectors
eigvals, eigvecs = np.linalg.eig(A)
print("\nEigenvalues of A:")
print(eigvals)
print("\nEigenvectors (each column is an eigenvector):")
print(eigvecs)


Matrix A:
[[4. 7. 2.]
 [3. 5. 1.]
 [2. 4. 3.]]

Determinant of A: -1.0

Inverse of A:
[[-11.  13.   3.]
 [  7.  -8.  -2.]
 [ -2.   2.   1.]]

Eigenvalues of A:
[10.231106 -0.05363   1.822523]

Eigenvectors (each column is an eigenvector):
[[-0.719526 -0.839246 -0.044166]
 [-0.50398   0.525699 -0.261727]
 [-0.477793 -0.138951  0.964131]]


In [ ]:
# Question 2.

# Create two arrays with specified shapes
np.random.seed(0)  # seed for reproducible random example
B = np.random.randint(1, 10, size=(2, 3))
C = np.random.randint(1, 10, size=(3, 2))

print("Matrix B (2x3):")
print(B)
print("\nMatrix C (3x2):")
print(C)

# Matrix multiplication (result will be shape (2,2))
product = B @ C   # equivalent to np.matmul(B, C)
print("\nProduct B @ C (2x2):")
print(product)


Matrix B (2x3):
[[6 1 4]
 [4 8 4]]

Matrix C (3x2):
[[6 3]
 [5 8]
 [7 9]]

Product B @ C (2x2):
[[ 69  62]
 [ 92 112]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [43]:
# Question 1.
arr3 = np.arange(1,10).reshape(3,3)
print('original array :')
print(arr3)

# Reshape to (1x9)
reshape_arr = arr.reshape(1,9)
print(' \nReshaped (3x3) Array to  (1x9)')
print(reshape_arr)

# Reshaped (3x3) Array to (9x1)
reshape_arr1 = arr.reshape(9,1)
print('\nReshaped (3x3) Array to (9x1)')
print(reshape_arr1)

original array :
[[1 2 3]
 [4 5 6]
 [7 8 9]]
 
Reshaped (3x3) Array to  (1x9)
[[1 2 3 4 5 6 7 8 9]]

Reshaped (3x3) Array to (9x1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [45]:
# Question 2.
arr_org = np.random.randint(1,50,size=(5,5))
print('Original Array (5x5)')
print(arr_org)

# Flatten the array

flatten_arr = arr_org.flatten()
print('\nFlatten Array ')
print(flatten_arr)

# Reshape flatten array back to (5x5)

org_arr = flatten_arr.reshape(5,5)
print('Reshaped to (5x5)')
print(org_arr)

Original Array (5x5)
[[20 15 40 33  2]
 [10 33 32 11 24]
 [36 12 29 35  1]
 [ 1 37  6 39 41]
 [18 16  5 42 43]]

Flatten Array 
[20 15 40 33  2 10 33 32 11 24 36 12 29 35  1  1 37  6 39 41 18 16  5 42
 43]
Reshaped to (5x5)
[[20 15 40 33  2]
 [10 33 32 11 24]
 [36 12 29 35  1]
 [ 1 37  6 39 41]
 [18 16  5 42 43]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [46]:
# Question 1.
# Create 5x5 random integer array
arr = np.random.randint(1, 50, size=(5, 5))
print("Original Array:")
print(arr)

# Fancy indexing to extract corners
corners = arr[[0, -1]][:, [0, -1]]

print("\nCorner Elements:")
print(corners)

Original Array:
[[32  2  2 40 42]
 [36 39 12 47 19]
 [28  1 15 36 13]
 [43 21 12  5  7]
 [ 5 48  4 13 37]]

Corner Elements:
[[32 42]
 [ 5 37]]


In [47]:
# Question 2.
 # Create 4x4 random integer array
arr2 = np.random.randint(1, 30, size=(4, 4))
print("Original Array:")
print(arr2)

# Boolean indexing to assign values
arr2[arr2 > 10] = 10

print("\nArray after setting values > 10 to 10:")
print(arr2)


Original Array:
[[21  9 15 16]
 [21  4 27 24]
 [16 14 22 22]
 [17 18  6 10]]

Array after setting values > 10 to 10:
[[10  9 10 10]
 [10  4 10 10]
 [10 10 10 10]
 [10 10  6 10]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [48]:
# Question 1.
# Create structured array data type
dtype = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]

# Add data
data = np.array([
    ('Alok', 24, 68.5),
    ('Ravi', 19, 55.2),
    ('Sneha', 22, 60.3),
    ('Mohan', 28, 72.0)
], dtype=dtype)

print("Original Array:")
print(data)

# Sort by age
sorted_data = np.sort(data, order='age')

print("\nSorted by Age:")
print(sorted_data)

Original Array:
[('Alok', 24, 68.5) ('Ravi', 19, 55.2) ('Sneha', 22, 60.3)
 ('Mohan', 28, 72. )]

Sorted by Age:
[('Ravi', 19, 55.2) ('Sneha', 22, 60.3) ('Alok', 24, 68.5)
 ('Mohan', 28, 72. )]


In [49]:
# Question 2.
# Create structured array for 2D points
dtype = [('x', 'i4'), ('y', 'i4')]

points = np.array([
    (1, 2),
    (3, 4),
    (6, 8),
    (2, 1)
], dtype=dtype)

print("Points:")
print(points)

# Extract x and y as arrays
x = points['x']
y = points['y']

# Compute Euclidean distance from origin (0,0)
distances = np.sqrt(x**2 + y**2)

print("\nEuclidean Distance of Each Point from Origin:")
print(distances)

Points:
[(1, 2) (3, 4) (6, 8) (2, 1)]

Euclidean Distance of Each Point from Origin:
[ 2.23606798  5.         10.          2.23606798]


In [ ]:
from scipy.spatial.distance import pdist, squareform

coords = np.column_stack((points['x'], points['y']))

pairwise_distances = squareform(pdist(coords))

print("\nPairwise Euclidean Distance Matrix:")
print(pairwise_distances)


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [50]:
# Question 1.
import numpy.ma as ma

# Create random array
arr = np.random.randint(1, 20, size=(4, 4))
print("Original Array:\n", arr)

# Mask values greater than 10
masked_arr = ma.masked_greater(arr, 10)
print("\nMasked Array:\n", masked_arr)

# Sum of unmasked values
sum_unmasked = masked_arr.sum()
print("\nSum of Unmasked Elements:", sum_unmasked)

Original Array:
 [[ 4  1  6  1]
 [18 19  5  3]
 [17  4  3 11]
 [14 17  8 10]]

Masked Array:
 [[4 1 6 1]
 [-- -- 5 3]
 [-- 4 3 --]
 [-- -- 8 10]]

Sum of Unmasked Elements: 45


In [51]:
# Question 2.
# Create random 3x3 array
arr2 = np.random.randint(1, 20, size=(3, 3))
print("Original Array:\n", arr2)

# Mask diagonal elements
masked_arr2 = ma.array(arr2, mask=np.eye(3, dtype=bool))
print("\nMasked Array:\n", masked_arr2)

# Compute mean of unmasked elements
mean_unmasked = masked_arr2.mean()
print("\nMean of Unmasked Elements:", mean_unmasked)

# Fill masked elements with the mean
filled_arr = masked_arr2.filled(mean_unmasked)
print("\nArray After Replacing Masked Diagonal:\n", filled_arr)


Original Array:
 [[ 1 11 19]
 [12  3  3]
 [ 4  4 19]]

Masked Array:
 [[-- 11 19]
 [12 -- 3]
 [4 4 --]]

Mean of Unmasked Elements: 8.833333333333334

Array After Replacing Masked Diagonal:
 [[ 8 11 19]
 [12  8  3]
 [ 4  4  8]]
